name: TensorBase Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: TensorBase Build
      run: CARGO_PROFILE_RELEASE_LTO='thin' CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 cargo build --release
    - name: TensorBase Archive
      run: zip -j base_linux.zip target/release/server crates/server/tests/confs/base.conf
    - run: touch CHANGELOG.md
    - name: TensorBase Create Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: base_linux.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "nightly build. Download repacked ClickHouse client: [clickhouse_client_repack_linux.zip](https://github.com/tensorbase/tensorbase/releases/download/v2021.07.05/clickhouse_client_repack_linux.zip)."

    
